### ISSUE TITLE
Error in train-classification/train.py

### ISSUE THREAD

**Issue by StefaniaTp** [huseinzol05/YOLO-Object-Detection-Tensorflow#3]
Hi, running your code with my own dataset, I encounter this type of error:
     File "train.py", line 39, in <module>
          data, output_dimension, label = utils.get_dataset()
     NameError: name 'utils' is not defined

Could you help me?

**Comment by jarrodhaas** [comment]
hi,

  I'm not the author of the code, but I have been working with it for the past couple of days. The issue there is that the get_dataset() function is listed at just above in the same file, its not actually in the utils.py file. 

  This is just one error of many that you'll encounter trying to use this code. if you're python / tensorflow skills are reasonably good, you can fight you're way through it, otherwise it's going to be near impossible to get training working correctly. Getting the network to run on pretrained weights is not too difficult tho. 

Good luck!

**Comment by huseinzol05** [comment]
hi! sorry for the trouble, later i recheck the problem.

**Comment by StefaniaTp** [comment]
Just few minutes after my comment, I tried deleting "utils" part and the code continued to run until the next error :) 
But I manage to fix most of them. My only problem yesterday was the doubt of missing files presence, as happens sometimes on Github.

Thank you both!

**Comment by ameyakale603** [comment]
@StefaniaTp 

can you post or paste your "train.py"
I am getting this error

Traceback (most recent call last):
  File "train.py", line 60, in <module>
    image = misc.imread(location + data[k + x, 0])
NameError: name 'location' is not defined


Thanks in advance

**Comment by StefaniaTp** [comment]
`import settings
import model
import os
import time
import numpy as np
import tensorflow as tf
from scipy import misc
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics

def get_dataset():
    
    list_folder = os.listdir('data/')
    list_images = []
    for i in xrange(len(list_folder)):
        images = os.listdir('data/' + list_folder[i])
        for x in xrange(len(images)):
            image = [list_folder[i] + '/' + images[x], list_folder[i]]
            list_images.append(image)
    list_images = np.array(list_images)
    np.random.shuffle(list_images)
    
    print "before cleaning got: " + str(list_images.shape[0]) + " data"
    
    list_temp = []
    for i in xrange(list_images.shape[0]):
        image = misc.imread('data/' + list_images[i, 0])
        if len(image.shape) < 3:
            continue
        list_temp.append(list_images[i, :].tolist())
        
    list_images = np.array(list_temp)
    print "after cleaning got: " + str(list_images.shape[0]) + " data"
    label = np.unique(list_images[:, 1]).tolist()
    list_images[:, 1] = LabelEncoder().fit_transform(list_images[:, 1]) 

    return list_images, np.unique(list_images[:, 1]).shape[0], label

data, output_dimension, label = get_dataset()
data, data_test = train_test_split(data, test_size = 0.2)

sess = tf.InteractiveSession()
model = model.Model(output_dimension)
sess.run(tf.global_variables_initializer())
saver = tf.train.Saver(tf.global_variables())


save_path = saver.save(sess, os.getcwd() + "/model.ckpt")

try:
    saver.restore(sess, os.getcwd() + "/model.ckpt")
    print "load model.."
except:
    print 'start from fresh variables'
    
for i in xrange(settings.epoch):
    print 'i ' + str(i)
    total_cost, total_accuracy, last_time, model.train = 0, 0, time.time(), True
    for k in xrange(0, (data.shape[0] // settings.batch_size) * settings.batch_size, settings.batch_size):
	print 'k ' + str(k)
        emb_data = np.zeros((settings.batch_size, settings.image_size, settings.image_size, 3), dtype = np.float32)
        emb_data_label = np.zeros((settings.batch_size, output_dimension), dtype = np.float32)
        
	location = './data/'
        for x in xrange(settings.batch_size):
            image = misc.imread(location + data[k + x, 0])
            image = misc.imresize(image, (settings.image_size, settings.image_size))
            emb_data_label[x, int(data[k + x, 1])] = 1.0
            emb_data[x, :, :, :] = image
            
        _, loss = sess.run([model.optimizer, model.cost], feed_dict = {model.X : emb_data, model.Y : emb_data_label})
        accuracy = sess.run(model.accuracy, feed_dict = {model.X : emb_data, model.Y : emb_data_label})
        total_cost += loss
        total_accuracy += accuracy
        
    total_cost /= (data.shape[0] // settings.batch_size)
    total_accuracy /= (data.shape[0] // settings.batch_size)
    print "epoch: " + str(i + 1) + ", loss: " + str(loss) + ", accuracy: " + str(accuracy) + ", s / epoch: " + str(time.time() - last_time)
    
    model.train, total_accuracy, total_logits = False, 0, []
    prova = np.zeros((data_test.shape[0] // settings.batch_size) * settings.batch_size)

    for k in xrange(0, (data_test.shape[0] // settings.batch_size) * settings.batch_size, settings.batch_size):
        emb_data = np.zeros((settings.batch_size, settings.image_size, settings.image_size, 3), dtype = np.float32)
        emb_data_label = np.zeros((settings.batch_size, output_dimension), dtype = np.float32)
        
	print 'k2 ' + str(k)
        for x in xrange(settings.batch_size):
            image = misc.imread(location + data_test[k + x, 0])
            image = misc.imresize(image, (settings.image_size, settings.image_size))
            emb_data_label[x, int(data_test[k + x, 1])] = 1.0
            emb_data[x, :, :, :] = image
	    prova[k+x] = data_test[k+x, 1]
	    
	print 'emb_data_label ' + str(emb_data_label)

	cast_logits =  tf.cast(tf.argmax(model.logits, 1), tf.int32)
        accuracy, logits = sess.run([model.accuracy, cast_logits], feed_dict = {model.X : emb_data, model.Y : emb_data_label})

        total_accuracy += accuracy
        total_logits += logits.tolist()
	print 'LOGITS ' + str(logits)
    
    total_accuracy /= (data_test.shape[0] // settings.batch_size)
    print 'testing accuracy: ' + str(total_accuracy)
   
    print 'prova ' + str(prova)
    stamp = metrics.classification_report(prova, np.array(total_logits), target_names = label)
    print str(stamp)
    
    saver.save(sess, os.getcwd() + '/model.ckpt')

`

**Comment by StefaniaTp** [comment]
import settings
import model
import os
import time
import numpy as np
import tensorflow as tf
from scipy import misc
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics

def get_dataset():
    
    list_folder = os.listdir('data/')
    list_images = []
    for i in xrange(len(list_folder)):
        images = os.listdir('data/' + list_folder[i])
        for x in xrange(len(images)):
            image = [list_folder[i] + '/' + images[x], list_folder[i]]
            list_images.append(image)
    list_images = np.array(list_images)
    np.random.shuffle(list_images)
    
    print "before cleaning got: " + str(list_images.shape[0]) + " data"
    
    list_temp = []
    for i in xrange(list_images.shape[0]):
        image = misc.imread('data/' + list_images[i, 0])
        if len(image.shape) < 3:
            continue
        list_temp.append(list_images[i, :].tolist())
        
    list_images = np.array(list_temp)
    print "after cleaning got: " + str(list_images.shape[0]) + " data"
    label = np.unique(list_images[:, 1]).tolist()
    list_images[:, 1] = LabelEncoder().fit_transform(list_images[:, 1]) 

    return list_images, np.unique(list_images[:, 1]).shape[0], label

data, output_dimension, label = get_dataset()
data, data_test = train_test_split(data, test_size = 0.2)

sess = tf.InteractiveSession()
model = model.Model(output_dimension)
sess.run(tf.global_variables_initializer())
saver = tf.train.Saver(tf.global_variables())


save_path = saver.save(sess, os.getcwd() + "/model.ckpt")

try:
    saver.restore(sess, os.getcwd() + "/model.ckpt")
    print "load model.."
except:
    print 'start from fresh variables'
    
for i in xrange(settings.epoch):
    print 'i ' + str(i)
    total_cost, total_accuracy, last_time, model.train = 0, 0, time.time(), True
    for k in xrange(0, (data.shape[0] // settings.batch_size) * settings.batch_size, settings.batch_size):
	print 'k ' + str(k)
        emb_data = np.zeros((settings.batch_size, settings.image_size, settings.image_size, 3), dtype = np.float32)
        emb_data_label = np.zeros((settings.batch_size, output_dimension), dtype = np.float32)
        
	location = './data/'
        for x in xrange(settings.batch_size):
            image = misc.imread(location + data[k + x, 0])
            image = misc.imresize(image, (settings.image_size, settings.image_size))
            emb_data_label[x, int(data[k + x, 1])] = 1.0
            emb_data[x, :, :, :] = image
            
        _, loss = sess.run([model.optimizer, model.cost], feed_dict = {model.X : emb_data, model.Y : emb_data_label})
        accuracy = sess.run(model.accuracy, feed_dict = {model.X : emb_data, model.Y : emb_data_label})
        total_cost += loss
        total_accuracy += accuracy
        
    total_cost /= (data.shape[0] // settings.batch_size)
    total_accuracy /= (data.shape[0] // settings.batch_size)
    print "epoch: " + str(i + 1) + ", loss: " + str(loss) + ", accuracy: " + str(accuracy) + ", s / epoch: " + str(time.time() - last_time)
    
    model.train, total_accuracy, total_logits = False, 0, []
    prova = np.zeros((data_test.shape[0] // settings.batch_size) * settings.batch_size)

    for k in xrange(0, (data_test.shape[0] // settings.batch_size) * settings.batch_size, settings.batch_size):
        emb_data = np.zeros((settings.batch_size, settings.image_size, settings.image_size, 3), dtype = np.float32)
        emb_data_label = np.zeros((settings.batch_size, output_dimension), dtype = np.float32)
        
	print 'k2 ' + str(k)
        for x in xrange(settings.batch_size):
            image = misc.imread(location + data_test[k + x, 0])
            image = misc.imresize(image, (settings.image_size, settings.image_size))
            emb_data_label[x, int(data_test[k + x, 1])] = 1.0
            emb_data[x, :, :, :] = image
	    prova[k+x] = data_test[k+x, 1]
	    
	print 'emb_data_label ' + str(emb_data_label)

	cast_logits =  tf.cast(tf.argmax(model.logits, 1), tf.int32)
        accuracy, logits = sess.run([model.accuracy, cast_logits], feed_dict = {model.X : emb_data, model.Y : emb_data_label})

        total_accuracy += accuracy
        total_logits += logits.tolist()
	print 'LOGITS ' + str(logits)
    
    total_accuracy /= (data_test.shape[0] // settings.batch_size)
    print 'testing accuracy: ' + str(total_accuracy)
   
    print 'prova ' + str(prova)
    stamp = metrics.classification_report(prova, np.array(total_logits), target_names = label)
    print str(stamp)
    
    saver.save(sess, os.getcwd() + '/model.ckpt')

**Comment by StefaniaTp** [comment]
Hi @onlyak, sorry for my late answer. I don't know very well how to use the issue part, so sorry for the notifications. I hope that I attach the file in the correct way, just change the extension ;)
[train.txt](https://github.com/huseinzol05/YOLO-Object-Detection-Tensorflow/files/1601774/train.txt)

Besides, I don't know if it's my fault or there is something else that is wrong in the code, but, when the following line is running, I always get the number of the last class (which is wrong, obviously). Could someone help me?
                accuracy, logits = sess.run([model.accuracy, tf.cast(tf.argmax(model.logits, 1), tf.int32)], feed_dict = {model.X : emb_data, model.Y : emb_data_label})

**Comment by SandeepSreenivasan** [comment]
I tried and fixed all the issues, but the training won't start. It says:
  File "train.py", line 72, in <module>
    _, loss = sess.run([model.optimizer, model.cost], feed_dict = {model.X : emb_data, model.Y : emb_data_label})
AttributeError: Model instance has no attribute 'X'
Can someone help me out with this issue
Thanks in advance
